title: David Yamnitsky
description: David Yamnitsky's Blog
url: davidyamnitsky.com
author:
    twitter: davidyamnitsky
twitter:
    username: davidyamnitsky
disqus_shortname: davidyamnitsky
gems:
  - jekyll-paginate
  - jekyll-feed
  - jemoji
  - jekyll-seo-tag
paginate: 10
permalink: pretty
excerpt_separator: <!-- excerpt -->
kramdown:
  input: GFM
  syntax_highlighter: rouge

