title: David Yamnitsky
uglyURLs: true
params:
  disqus_shortname: davidyamnitsky
baseURL: https://www.davidyamnitsky.com/
permalinks:
  blog: /:section/:year/:month/:day/:slug
metaDataFormat: yaml
enableRobotsTXT: true
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
pygmentsUseClasses: true
pygmentsOptions:
  - linenos
enableEmoji: true
blackfriday:
  extensions:
    - hardLineBreak
---
